defaults:
  - model: model
  - train: train
  - eval: eval
  - dataset: dataset
  - base: default
  - _self_

base:
  wandb_project_name: "my_project_name"
  wandb_entity: "my_entity"

  device: "cpu"