defaults:
  - model: model
  - train: train
  - eval: eval
  - dataset: dataset
  - _self_

base:
  wandb_project_name: "DIHT"
  wandb_entity: "entropeaks-universit-paul-sabatier-toulouse-iii"

  device: "cuda"