wandb:
  project_name: "DIHT"
  entity: "entropeaks-universit-paul-sabatier-toulouse-iii"
data:
  dataset_path: "augmented_data16"
  test_size: 0.2
  sampler:
    P: 16
    K: 4
model:
  base_model_name: "facebook/dinov3-vitl16-pretrain-lvd1689m"
  hidden_dim: 512
  output_dim: 128
  normalize: true
  dropout: 0
training:
  epochs: 200
  lr: 0.00005
  weight_decay: 0.0001
  margin: 0.7
evaluation:
  recall_k: [1, 3, 10]
  test_size: 0.3