wandb:
  project_name: "DIHT"
  entity: "entropeaks-universit-paul-sabatier-toulouse-iii"
data:
  dataset_path: "augmented_data16"
  test_size: 0.2
  sampler:
    P: [4, 8, 16, 32]
    K: [4, 8, 16]
model:
  base_model_name: "facebook/dinov3-vitb16-pretrain-lvd1689m"
  dropout: [0.0, 0.5]
  output_dim: [32, 64, 128, 256]
  hidden_dim: [256, 512]

training:
  epochs: [1, 50]
  lr: [0.000001, 0.0001]
  weight_decay: [0.0000001, 0.0001]
  margin: [0.5, 2.0]

evaluation:
  recall_k: [1, 3, 10]
  test_size: 0.3

n_trials: 50